In [1]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = make_classification(
    n_samples=2000,
    n_features=21,
    n_informative=18,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size=0.2
)

In [3]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)
y_pred = model_lr.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_lr.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  0.80125
Testing accuracy:  0.795
Recall:  0.8121827411167513
Precision:  0.7804878048780488
confusion matric: 
 [[158  45]
 [ 37 160]]


In [4]:
pipeline = Pipeline([
    ("lr", LogisticRegression())
])

param_grid = [
    {
        "lr__solver": ["liblinear"],
        "lr__penalty": ["l1", "l2"],
        "lr__C": [0.1, 0.5, 1, 5, 10],
        "lr__class_weight": ["balanced"],
        "lr__max_iter": [100, 300, 500]
    },
    {
        "lr__solver": ["saga"],
        "lr__penalty": ["l1", "l2", "elasticnet"],
        "lr__l1_ratio": [0.2, 0.5, 0.8],  # only used for elasticnet
        "lr__C": [0.1, 0.5, 1, 5, 10],
        "lr__class_weight": ["balanced"],
        "lr__max_iter": [100, 300, 500]
    },
    {
        "lr__solver": ["lbfgs"],
        "lr__penalty": ["l2"],
        "lr__C": [0.1, 0.5, 1, 5, 10],
        "lr__class_weight": ["balanced"],
        "lr__max_iter": [100, 300, 500]
    }
]

model_lr_cv = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv = 5,
    n_jobs=-1
)

model_lr_cv.fit(X_train, y_train)
y_pred = model_lr_cv.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_lr_cv.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  0.803125
Testing accuracy:  0.795
Recall:  0.8121827411167513
Precision:  0.7804878048780488
confusion matric: 
 [[158  45]
 [ 37 160]]


In [6]:
from sklearn.neighbors import KNeighborsClassifier

scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

model_knn = KNeighborsClassifier()
model_knn.fit(X_train_scale, y_train)
y_pred = model_knn.predict(X_test_scale)

print("Training accuracy: ",accuracy_score(y_train, model_knn.predict(X_train_scale)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  0.975
Testing accuracy:  0.9575
Recall:  0.9746192893401016
Precision:  0.9411764705882353
confusion matric: 
 [[191  12]
 [  5 192]]


In [6]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier())
])

param_grid = [
    {
    "knn__n_neighbors" : [3, 5, 7, 9, 11, 13, 15],
    "knn__weights" : ["uniform", "distance"],
    "knn__algorithm" : ["auto", "brute"],
    "knn__p" : [1, 2]
    },
    {
    "knn__n_neighbors" : [3, 5, 7, 9, 11, 13, 15],
    "knn__weights" : ["uniform", "distance"],
    "knn__algorithm" : ["ball_tree", "kd_tree"],
    "knn__p" : [1, 2]
    }
]

model_knn_cv = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv = 5,
    n_jobs=-1
)

model_knn_cv.fit(X_train, y_train)
y_pred = model_knn_cv.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_knn_cv.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  0.97
Testing accuracy:  0.9675
Recall:  0.9746192893401016
Precision:  0.96
confusion matric: 
 [[195   8]
 [  5 192]]


In [7]:
from sklearn.naive_bayes import GaussianNB

model_nb = GaussianNB()
model_nb.fit(X_train, y_train)
y_pred = model_nb.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_nb.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  0.78875
Testing accuracy:  0.77
Recall:  0.817258883248731
Precision:  0.7419354838709677
confusion matric: 
 [[147  56]
 [ 36 161]]


In [8]:
model_nb_cv = GridSearchCV(
    estimator=GaussianNB(),
    param_grid={"var_smoothing": [1e-12, 1e-11, 1e-10, 1e-9, 1e-8]},
    cv = 5,
    n_jobs=-1
)

model_nb_cv.fit(X_train, y_train)
y_pred = model_nb_cv.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_nb_cv.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  0.78875
Testing accuracy:  0.77
Recall:  0.817258883248731
Precision:  0.7419354838709677
confusion matric: 
 [[147  56]
 [ 36 161]]


In [6]:
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier()

model_dt.fit(X_train_scale, y_train)
y_pred = model_dt.predict(X_test_scale)

print("Training accuracy: ",accuracy_score(y_train, model_dt.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

NameError: name 'X_train_scale' is not defined

In [19]:
pipeline = Pipeline([
    ("dt", DecisionTreeClassifier(random_state=42))
])

param_grid = {
    "dt__criterion": ["gini", "entropy"],
    "dt__max_depth": [5, 6, 7, 8, 9, 10],
    "dt__min_samples_split": [2, 5, 6, 7, 8, 9, 10],
    "dt__min_samples_leaf": [1, 2, 3, 4, 5],
    "dt__max_features": ["sqrt", "log2", None]
}

model_dt_cv = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv = 5,
    n_jobs=-1
)

model_dt_cv.fit(X_train, y_train)
y_pred = model_dt_cv.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_dt_cv.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

print("Best Parameters:", model_dt_cv.best_params_)
print("Best CV Score:", model_dt_cv.best_score_)

Training accuracy:  0.92875
Testing accuracy:  0.825
Recall:  0.817258883248731
Precision:  0.8256410256410256
confusion matric: 
 [[169  34]
 [ 36 161]]
Best Parameters: {'dt__criterion': 'gini', 'dt__max_depth': 8, 'dt__max_features': None, 'dt__min_samples_leaf': 2, 'dt__min_samples_split': 5}
Best CV Score: 0.7837500000000001


In [8]:
from sklearn.svm import SVC

model_svc = SVC()
model_svc.fit(X_train_scale, y_train)
y_pred = model_svc.predict(X_test_scale)

print("Training accuracy: ",accuracy_score(y_train, model_svc.predict(X_train_scale)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))


Training accuracy:  0.98625
Testing accuracy:  0.9775
Recall:  0.9796954314720813
Precision:  0.9747474747474747
confusion matric: 
 [[198   5]
 [  4 193]]


In [9]:
import numpy as np

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svc", SVC(random_state=42))
])

param_grid = [
{
    "svc__C": np.arange(0.1, 2.1, 0.1),
    "svc__kernel" : ["linear","rbf", "sigmoid"],
    "svc__degree" : [x for x in range(1, 11)],
    "svc__gamma" : ["auto", "scale"],
    "svc__class_weight" : ["balanced"]
},
{
    "svc__C": np.arange(0.1, 2.1, 0.1),
    "svc__kernel" : ["poly"],
    "svc__degree" : [x for x in range(1, 11)],
    "svc__gamma" : ["auto", "scale"],
    "svc__class_weight" : ["balanced"]
}
]

model_svc_cv = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv = 5,
    n_jobs=-1
)

model_svc_cv.fit(X_train, y_train)
y_pred = model_svc_cv.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_svc_cv.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

print("Best Parameters:", model_svc_cv.best_params_)
print("Best CV Score:", model_svc_cv.best_score_)

Training accuracy:  0.99125
Testing accuracy:  0.9825
Recall:  0.9898477157360406
Precision:  0.975
confusion matric: 
 [[198   5]
 [  2 195]]
Best Parameters: {'svc__C': np.float64(1.8000000000000003), 'svc__class_weight': 'balanced', 'svc__degree': 1, 'svc__gamma': 'auto', 'svc__kernel': 'rbf'}
Best CV Score: 0.9731249999999999


In [4]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()
model_rf.fit(X_train, y_train)
y_pred = model_rf.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_rf.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  1.0
Testing accuracy:  0.91
Recall:  0.9035532994923858
Precision:  0.9128205128205128
confusion matric: 
 [[186  17]
 [ 19 178]]


In [5]:
pipeline = Pipeline([
    ("rf", RandomForestClassifier(random_state=42))
])

param_grid = {
    "rf__criterion" : ["gini", "entropy", "log_loss"],
    "rf__max_depth" : [2, 3, 4, 5, 6, None],
    "rf__min_samples_split" : [2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20],
    "rf__min_samples_leaf" : [1, 2, 3, 4],
    "rf__max_features" : ["sqrt", "log2"],
    "rf__class_weight" : ["balanced"],
    "rf__n_estimators" : [101, 201, 301, 401, 501, 601, 701, 801, 901]
}

model_rf_cv = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv = 5,
    n_jobs=-1
)

model_rf_cv.fit(X_train, y_train)
y_pred = model_rf_cv.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_rf_cv.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

print("Best Parameters:", model_rf_cv.best_params_)
print("Best CV Score:", model_rf_cv.best_score_)

KeyboardInterrupt: 

In [9]:
from xgboost import XGBClassifier

model_xgb = XGBClassifier()
model_xgb.fit(X_train, y_train)
y_pred = model_xgb.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_xgb.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

Training accuracy:  1.0
Testing accuracy:  0.92
Recall:  0.9238578680203046
Precision:  0.914572864321608
confusion matric: 
 [[186  17]
 [ 15 182]]


In [11]:
pipeline = Pipeline([
    ("xgb", XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    ))
])

param_grid = {
    "xgb__n_estimators": [500, 600, 700, 800],
    "xgb__max_depth": [3, 5, 7],
    "xgb__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "xgb__subsample": [0.8, 1.0],
    "xgb__colsample_bytree": [0.8, 1.0]
}

model_xgb_cv = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv = 5,
    n_jobs=-1
)

model_xgb_cv.fit(X_train, y_train)
y_pred = model_xgb_cv.predict(X_test)

print("Training accuracy: ",accuracy_score(y_train, model_xgb_cv.predict(X_train)))
print("Testing accuracy: ", accuracy_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("confusion matric: \n", confusion_matrix(y_test, y_pred))

print("Best Parameters:", model_xgb_cv.best_params_)
print("Best CV Score:", model_xgb_cv.best_score_)

Training accuracy:  1.0
Testing accuracy:  0.94
Recall:  0.9390862944162437
Precision:  0.9390862944162437
confusion matric: 
 [[191  12]
 [ 12 185]]
Best Parameters: {'xgb__colsample_bytree': 1.0, 'xgb__learning_rate': 0.05, 'xgb__max_depth': 5, 'xgb__n_estimators': 800, 'xgb__subsample': 0.8}
Best CV Score: 0.943125


In [14]:
import pandas as pd

X_train_df = pd.DataFrame(X_train)
X_test_df = pd.DataFrame(X_test)

print(X_train_df.duplicated().sum())
print(X_test_df.duplicated().sum())

0
0
