In [1]:
import numpy as np

In [2]:
# create from list

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr2 = np.array([1, 2, 3, 4, 5, "apple"])
print(arr2)

['1' '2' '3' '4' '5' 'apple']


In [4]:
arr.shape

(5,)

In [5]:
arr2.shape

(6,)

In [6]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2D)
arr_2D.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

* Using build in function

In [ ]:
# np.arange() -> create an array with a range of values
arr = np.arange(1, 10, 1) # start, end, step
print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
# np.zeros() -> creating an array filled with zeroes

arr = np.zeros((2, 3))  # 2 row 3 column
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# np.ones() -> creates an array filled with ones

arr = np.ones((2, 3), dtype="int64")
print(arr)

[[1 1 1]
 [1 1 1]]


In [12]:
# np.full() -> create an array filled with the value we give

arr = np.full((2, 3), 8)
print(arr)

[[8 8 8]
 [8 8 8]]


In [13]:
# np.eye() -> create an array and filled the diagonal with "1" and "0" with remaining

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# np.linspace() -> it create evenly space over a specific range

arr = np.linspace(1, 100, 4) # start, end, total number of value
print(arr)

[  1.  34.  67. 100.]
