In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
arr.shape # it print dimension -> (raw, column)

(2, 3)

In [4]:
arr.size # total element

6

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.ndim # it print the dimension

2

In [7]:
# type casting from existing array

float_arr = arr.astype(np.float64)
float_arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
# type casting on creating time

arr = np.zeros((3, 4), dtype="int64")
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
