In [1]:
import numpy as np

1D -> 1 Axis (axis 0)

2D -> 2 Axis
1) axis 0 -- rows
2) axis 1 -- columns

3D -> 3 Axis
1) axis 0 -- depth or layers
2) axis 1 -- row in each column
3) axis 2 -- column

In [2]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2D)

print(np.sum(arr_2D))

sum_of_col = np.sum(arr_2D, axis=0)
print(sum_of_col)

sum_of_row = np.sum(arr_2D, axis=1)
print(sum_of_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [3]:
# slicing

arr_2D_slic = arr_2D[0:2, 1:2]
arr_2D_slic

array([[2],
       [5]])

In [6]:
# 3D array

arr_3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) # 2 X 3 X 2

print(arr_3D, arr_3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [9]:
# indexing  

# target 4
print(arr_3D[0, 1, 1])

# target 9
print(arr_3D[1, 1, 0])

4
9


In [13]:
# first row for both 2D array

print(arr_3D[0, 0], arr_3D[1, 0])

print(arr_3D[:, 0, :])

[1 2] [7 8]
[[1 2]
 [7 8]]


In [14]:
# first column

print(arr_3D[:, :, 0])

[[ 1  3  5]
 [ 7  9 11]]


In [17]:
# replacing all value for 1st row with 99

arr_3D[:, 0, :] = 99
print(arr_3D)

[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
