In [1]:
import numpy as np

In [2]:
# vectorization

arr = np.array([1, 2, 3, 4, 5])

In [3]:
print(arr)
print(arr ** 2)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [4]:
print(arr+10)

[11 12 13 14 15]


In [5]:
print(arr // 2)

[0 1 1 2 2]


* Broadcasting -> scalling our array without using extra memory

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])