In [1]:
import numpy as np

In [2]:
# vectorization

arr = np.array([1, 2, 3, 4, 5])

In [3]:
print(arr)
print(arr ** 2)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [4]:
print(arr+10)

[11 12 13 14 15]


In [5]:
print(arr // 2)

[0 1 1 2 2]


* Broadcasting -> scalling our array without using extra memory

it only work when both dimension are same or onew of them is 1

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5]) # 1 x 5
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]) # 2 x 5
print(arr1+arr2)

[[[ 2  4  6  8 10]
  [ 7  9 11 13  5]]]


In [7]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [1, 2, 3, 4, 5]]) # 3 x 5
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]) # 2 x 5
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

* Vector Normalization -> Normalizing an array means transforming its values so they fit into a specific scale or range

In [10]:
arr = np.array([[1, 2], [3, 4]])

mean = arr.mean()
std_dev = arr.std()

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
