In [35]:
import numpy as np

In [36]:
arr = np.array([1, 2, 3, 4, 5])

* Aggrigation Function

In [37]:
np.sum(arr)

np.int64(15)

In [38]:
np.prod(arr)

np.int64(120)

In [39]:
np.min(arr)

np.int64(1)

In [40]:
np.max(arr)

np.int64(5)

In [41]:
np.mean(arr)

np.float64(3.0)

In [42]:
np.median(arr)

np.float64(3.0)

In [43]:
np.std(arr)

np.float64(1.4142135623730951)

In [44]:
np.var(arr)

np.float64(2.0)

In [45]:
np.argmax(arr) # it print the index of a highest vale in an array

np.int64(4)

In [46]:
np.argmin(arr)

np.int64(0)

* power function

In [47]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [48]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

In [49]:
np.pow(arr, 3)

array([  1,   8,  27,  64, 125])

* Log & Exponential

In [50]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [51]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [55]:
arr = np.log2(arr)
arr

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [53]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

* Rounding

In [57]:
arr

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [ ]:
np.round(arr) # find the nearest one 

array([0., 1., 2., 2., 2.])

In [ ]:
np.floor(arr) # round down the value --- 3.12 -> 4

array([0., 1., 1., 2., 2.])

In [ ]:
np.ceil(arr) # round up the value -- 2.12 -> 2

array([0., 1., 2., 2., 3.])

In [ ]:
np.trunc(arr) # remove the remaining value after decimal

array([0., 1., 1., 2., 2.])