In [1]:
import numpy as np

In [2]:
# create from list

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr2 = np.array([1, 2, 3, 4, 5, "apple"])
print(arr2)

['1' '2' '3' '4' '5' 'apple']


In [5]:
arr.shape

(5,)

In [6]:
arr2.shape

(6,)

In [9]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2D)
arr_2D.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)