In [2]:
import numpy as np

* RESHAPING

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# reshape array

reshape_arr = arr.reshape((3, 2))
print(reshape_arr)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
# flattened 

flatened = arr.flatten() # convert 2D to 1D
flatened

array([1, 2, 3, 4, 5, 6])

* INDEXONG (1D & 2D array)

In [ ]:
# normnal indexing 

arr = np.array([1, 2, 3, 4, 5])

arr[0]

np.int64(1)

In [9]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2D)
print(arr_2D[1, 1])

[[1 2 3]
 [4 5 6]]
5


* Fancy and Boolean indexing

1) it can excess multiple index at same time
2) As for fancy indexing we can simply write the index number in a list
3) As for boolean it depending upon a particular condition -- if it true it print the value

In [ ]:
# Fancy indexing

arr = np.array([56, 67, 435, 22, 34])
idx = [1, 2, 3] # index that i want to excess
print(arr[idx])

[ 67 435  22]


In [12]:
# Boolean indexing

arr = np.array([1, 2, 3, 4, 5])

print(arr[arr % 2 == 0])
print(arr[arr > 2])

[2 4]
[3 4 5]


* Slicing

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:1]) # start : stop : step
print(arr[:])

[2 3 4 5]
[1 2 3 4 5 6 7]


* Copy vs View in slicing

In [16]:
py_lst = [1, 2, 3, 4, 5]
sub_lst = py_lst[1:3]
print(sub_lst)

sub_lst[0] =  200
print(sub_lst)
print(py_lst)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [17]:
np_arr = np.array([1, 2, 3, 4, 5])
sub_arr = np_arr[1:3]
print(sub_arr)

sub_arr[0] = 10
print(sub_arr)
print(np_arr)

[2 3]
[10  3]
[ 1 10  3  4  5]
